language: node_js

sudo: required

node_js:
  - "5.1.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - make
      - git
      - gcc-4.8
      - g++-4.8
      - lcov
